package avl_tree;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class Base extends javax.swing.JPanel {

    private LinkedListAVL_Tree avlTree = new LinkedListAVL_Tree();
    private TreeDisplayPanel displayPanel = new TreeDisplayPanel();

    public Base() {
        initComponents();
        displayPanel.setBackground(Color.WHITE);
        Display.setLayout(new BorderLayout());
        Display.add(displayPanel, BorderLayout.CENTER);

        // Ensure that ShowTraverse has space
        addKeyListeners();
    }

    private void addKeyListeners() {
        insertBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    insert_BtnActionPerformed(null);
                }
            }
        });

        deleteBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    delete_BtnActionPerformed(null);
                }
            }
        });

        findBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    find_BtnActionPerformed(null);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        HeaderBG = new javax.swing.JLabel();
        controlBtn = new javax.swing.JPanel();
        print_Btn = new javax.swing.JButton();
        insertBox = new javax.swing.JTextField();
        insert_Btn = new javax.swing.JButton();
        deleteBox = new javax.swing.JTextField();
        delete_Btn = new javax.swing.JButton();
        findBox = new javax.swing.JTextField();
        find_Btn = new javax.swing.JButton();
        Display = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaOnDisplay = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));

        header.setBackground(new java.awt.Color(17, 117, 84));
        header.setForeground(java.awt.Color.white);

        HeaderBG.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        HeaderBG.setForeground(new java.awt.Color(255, 235, 0));
        HeaderBG.setText("AVL Tree");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeaderBG)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HeaderBG))
        );

        controlBtn.setBackground(new java.awt.Color(110, 194, 7));
        controlBtn.setPreferredSize(new java.awt.Dimension(700, 25));

        print_Btn.setText("Print");
        print_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_BtnActionPerformed(evt);
            }
        });

        insertBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                insertBoxMouseEntered(evt);
            }
        });
        insertBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBoxActionPerformed(evt);
            }
        });

        insert_Btn.setText("Insert");
        insert_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_BtnActionPerformed(evt);
            }
        });

        deleteBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBoxActionPerformed(evt);
            }
        });

        delete_Btn.setText("Delete");
        delete_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_BtnActionPerformed(evt);
            }
        });

        findBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBoxActionPerformed(evt);
            }
        });

        find_Btn.setText("Find");
        find_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                find_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlBtnLayout = new javax.swing.GroupLayout(controlBtn);
        controlBtn.setLayout(controlBtnLayout);
        controlBtnLayout.setHorizontalGroup(
            controlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlBtnLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(insertBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insert_Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete_Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(find_Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(print_Btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlBtnLayout.setVerticalGroup(
            controlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(insertBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(deleteBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(findBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(insert_Btn)
                .addComponent(delete_Btn)
                .addComponent(find_Btn)
                .addComponent(print_Btn))
        );

        Display.setBackground(new java.awt.Color(255, 255, 255));
        Display.setPreferredSize(new java.awt.Dimension(700, 500));

        TextAreaOnDisplay.setColumns(20);
        TextAreaOnDisplay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TextAreaOnDisplay.setRows(5);
        jScrollPane1.setViewportView(TextAreaOnDisplay);

        javax.swing.GroupLayout DisplayLayout = new javax.swing.GroupLayout(Display);
        Display.setLayout(DisplayLayout);
        DisplayLayout.setHorizontalGroup(
            DisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayLayout.createSequentialGroup()
                .addGap(734, 734, 734)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        DisplayLayout.setVerticalGroup(
            DisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Display, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                    .addComponent(header, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(controlBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(controlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Display, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void insertBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertBoxActionPerformed

    private void deleteBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBoxActionPerformed

    private void findBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findBoxActionPerformed

    private void insert_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_BtnActionPerformed
        // TODO add your handling code here:
        String input = insertBox.getText();
        try {
            int value = Integer.parseInt(input);
            avlTree.root = avlTree.insert(avlTree.root, value);
            insertBox.setText("");
            TextAreaOnDisplay.setText(avlTree.printTree());
            displayPanel.setTree(avlTree.root);
            JOptionPane.showMessageDialog(this, value + " inserted.");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid integer.");
        }
    }//GEN-LAST:event_insert_BtnActionPerformed

    private void delete_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_BtnActionPerformed
        // TODO add your handling code here:
        String input = deleteBox.getText();
        try {
            int value = Integer.parseInt(input);
            avlTree.root = avlTree.deleteNode(avlTree.root, value);
            deleteBox.setText("");
            TextAreaOnDisplay.setText(avlTree.printTree());
            displayPanel.setTree(avlTree.root);
            JOptionPane.showMessageDialog(this, value + " deleted.");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid integer.");
        }
    }//GEN-LAST:event_delete_BtnActionPerformed

    private void find_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_find_BtnActionPerformed
        // TODO add your handling code here:
        String input = findBox.getText();
        try {
            int value = Integer.parseInt(input);
            boolean found = avlTree.find(avlTree.root, value);
            JOptionPane.showMessageDialog(this, found ? (value + " found in the tree.") : (value + " not found in the tree."));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid integer.");
        }
    }//GEN-LAST:event_find_BtnActionPerformed

    private void print_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_BtnActionPerformed
        // TODO add your handling code here:
        String preOrderTraversal = avlTree.preOrder(avlTree.root);
        String inOrderTraversal = avlTree.inOrder(avlTree.root);
        String postOrderTraversal = avlTree.postOrder(avlTree.root);

        // Print results to the terminal
        System.out.println("Pre-order: " + preOrderTraversal);
        System.out.println("In-order: " + inOrderTraversal);
        System.out.println("Post-order: " + postOrderTraversal);

        // Optionally display a message dialog
        JOptionPane.showMessageDialog(this, "Traversal output printed in the terminal.");
    }//GEN-LAST:event_print_BtnActionPerformed

    private void insertBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertBoxMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_insertBoxMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Display;
    private javax.swing.JLabel HeaderBG;
    private javax.swing.JTextArea TextAreaOnDisplay;
    private javax.swing.JPanel controlBtn;
    private javax.swing.JTextField deleteBox;
    private javax.swing.JButton delete_Btn;
    private javax.swing.JTextField findBox;
    private javax.swing.JButton find_Btn;
    private javax.swing.JPanel header;
    private javax.swing.JTextField insertBox;
    private javax.swing.JButton insert_Btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton print_Btn;
    // End of variables declaration//GEN-END:variables
}
